name: "godot-ci export"
on:
  push:
    branches:
      - release

env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: the-scaley-cook-game
  ITCH_GAME: the-scaley-cook-game
  ITCH_USER: erebrus

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.3
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup
      run: |
        mkdir -v -p ~/.local/share/godot/export_templates
        mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
        ls ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
    - name: Web Build
      run: |
        cd godot
        mkdir -v -p build/windows
        godot -v --headless --export-release "Windows" build/windows/skaley.exe
    - name: Publish to Itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: windows
        PACKAGE: godot/build/windows
